### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by tcr** [tcr/edit-text#15]
* [x] Backspace in lists to join bullet groups to match splitting them
* [x] The monkey test that working
* [x] Then fixing the phantom empty skip group thing on multi when you start stop monkey
* [x] Then monkey test that thing
* [x] Then adding random click back in and debugging it, including using mercutio-replay to do so
* [x] Then having random click fix more bugs around multiple people using Mercutio
* [x] Then you have it resilient for launch
* [x] Add pages?
* [x] Add warning about this being demo software
* [ ] Write a talk.
* [ ] Test more usability fixes when testing out how to give a demo.
* [x] Add export
* [x] Add custom page names
* [x] Add bottom of page warning
* [ ] Add import(?)
* [ ] Remove carets from terminated clients(?)
